### ISSUE TITLE
Gluon Compiler ICE: Unexpected data type

### ISSUE THREAD

**Issue by endeav0r** [gluon-lang/gluon#356]
Steps to reproduce may be painful, sorry. First repo is used to create a docker which allows second repo to build. This process, end-to-end, will probably take 15 minutes. I may end up troubleshooting this one myself, but at least there's a note here.

```
git clone https://github.com/falconre/falcon
docker build -t falcon falcon
docker run --rm -ti falcon
apt-get install -y git
git clone https://github.com/falconre/osprey
git checkout f90d38f3359aa9e93d
cd osprey
cargo build
```

Place this gluon script somewhere:
```
let io = import! "std/io.glu"

let IlConstantNew value bits = constant_new value bits

let c = IlConstantNew 32 8

io.println "tests pass"
```

Now run osprey with
```
cargo run -- -s path/to/script.glu
```

OSX
```
MacBook-Pro:osprey dev$ RUST_BACKTRACE=full cargo run -- -s /tmp/test.glu
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/osprey -s /tmp/test.glu`
thread 'main' panicked at 'ICE: Unexpected data type: IlConstant', /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:779:25
stack backtrace:
   0:        0x107d61973 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h5d6b821bcccc8af3
   1:        0x107d62e9a - std::panicking::default_hook::{{closure}}::haca53f8b96e15b81
   2:        0x107d62b62 - std::panicking::default_hook::h0029f59c1ec97ffc
   3:        0x107d65102 - std::panicking::rust_panic_with_hook::hb8eae939c3fcaf9c
   4:        0x107d64f64 - std::panicking::begin_panic_new::h3c5f9a0be81106be
   5:        0x107d64eb2 - std::panicking::begin_panic_fmt::hf585b6224c51a06c
   6:        0x107830501 - gluon_vm::compiler::Compiler::compile_::h9801e7bc77c7dedc
   7:        0x10782c992 - gluon_vm::compiler::Compiler::compile::hebc4ad168141a748
   8:        0x10782d47e - gluon_vm::compiler::Compiler::compile_::h9801e7bc77c7dedc
   9:        0x10782c992 - gluon_vm::compiler::Compiler::compile::hebc4ad168141a748
  10:        0x10782f4dc - gluon_vm::compiler::Compiler::compile_::h9801e7bc77c7dedc
  11:        0x10782c992 - gluon_vm::compiler::Compiler::compile::hebc4ad168141a748
  12:        0x10782f4dc - gluon_vm::compiler::Compiler::compile_::h9801e7bc77c7dedc
  13:        0x10782c992 - gluon_vm::compiler::Compiler::compile::hebc4ad168141a748
  14:        0x10782f4dc - gluon_vm::compiler::Compiler::compile_::h9801e7bc77c7dedc
  15:        0x10782c992 - gluon_vm::compiler::Compiler::compile::hebc4ad168141a748
  16:        0x10782f4dc - gluon_vm::compiler::Compiler::compile_::h9801e7bc77c7dedc
  17:        0x10782c992 - gluon_vm::compiler::Compiler::compile::hebc4ad168141a748
  18:        0x10782f4dc - gluon_vm::compiler::Compiler::compile_::h9801e7bc77c7dedc
  19:        0x10782c992 - gluon_vm::compiler::Compiler::compile::hebc4ad168141a748
  20:        0x10782f4dc - gluon_vm::compiler::Compiler::compile_::h9801e7bc77c7dedc
  21:        0x10782c992 - gluon_vm::compiler::Compiler::compile::hebc4ad168141a748
  22:        0x10782f4dc - gluon_vm::compiler::Compiler::compile_::h9801e7bc77c7dedc
  23:        0x10782c992 - gluon_vm::compiler::Compiler::compile::hebc4ad168141a748
  24:        0x10782be95 - gluon_vm::compiler::Compiler::compile_expr::h460b2b385415ad1c
  25:        0x106de15d4 - <gluon::compiler_pipeline::TypecheckValue<E> as gluon::compiler_pipeline::Compileable<Extra>>::compile::hc0c926ff7a39a520
  26:        0x106dea640 - <T as gluon::compiler_pipeline::Compileable<core::option::Option<&'b gluon_base::types::ArcType>>>::compile::{{closure}}::h446600cf05312eff
  27:        0x106e29bb0 - <core::result::Result<T, E>>::and_then::h6c1e3469fbc9589b
  28:        0x106dea4fc - <T as gluon::compiler_pipeline::Compileable<core::option::Option<&'b gluon_base::types::ArcType>>>::compile::h35c0629616e06b43
  29:        0x106eda723 - <C as gluon::compiler_pipeline::Executable<'vm, Extra>>::run_expr::hc1987b1037202d42
  30:        0x106e88aae - gluon::Compiler::run_io_expr_async::hccf85dabd8f1cff1
  31:        0x106e8895d - gluon::Compiler::run_io_expr::h8c20ebe59f60c880
  32:        0x106f1a773 - osprey::bindings::run_code::h08f2d75326211d9a
  33:        0x106f1adc0 - osprey::osprey::hebffdff9d250f169
  34:        0x106f1af18 - osprey::main::h7902dbd542442a2a
  35:        0x107d661dc - __rust_maybe_catch_panic
  36:        0x107d65558 - std::rt::lang_start::heed3cc6f59fb65ca
  37:        0x106f1d1c9 - main
```

From inside the docker:
```
root@bee095af6bf9:~/osprey# RUST_BACKTRACE=full cargo run -- -s /tmp/test.glu 
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/osprey -s /tmp/test.glu`
thread 'main' panicked at 'ICE: Unexpected data type: IlConstant', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:779:25
stack backtrace:
   0:     0x56407f267243 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hcdf51e4c9dc54357
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x56407f263a74 - std::sys_common::backtrace::_print::h9da91fd31a37d0f1
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x56407f268883 - std::panicking::default_hook::{{closure}}::h46820a72bf0cb624
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:380
   3:     0x56407f2685f2 - std::panicking::default_hook::h4c1ef1cc83189c8e
                               at /checkout/src/libstd/panicking.rs:396
   4:     0x56407f268ce7 - std::panicking::rust_panic_with_hook::h99016f44bdcb8544
                               at /checkout/src/libstd/panicking.rs:611
   5:     0x56407f268bb4 - std::panicking::begin_panic_new::hae931f4b9fe56a90
                               at /checkout/src/libstd/panicking.rs:553
   6:     0x56407f268ab9 - std::panicking::begin_panic_fmt::h3b8db4524c33692e
                               at /checkout/src/libstd/panicking.rs:521
   7:     0x56407ed62ef1 - gluon_vm::compiler::Compiler::compile_::h543918283bcdae2d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:779
   8:     0x56407ed5f6c2 - gluon_vm::compiler::Compiler::compile::h60c6b4594eb7955d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:562
   9:     0x56407ed6010e - gluon_vm::compiler::Compiler::compile_::h543918283bcdae2d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:593
  10:     0x56407ed5f6c2 - gluon_vm::compiler::Compiler::compile::h60c6b4594eb7955d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:562
  11:     0x56407ed61f74 - gluon_vm::compiler::Compiler::compile_::h543918283bcdae2d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:740
  12:     0x56407ed5f6c2 - gluon_vm::compiler::Compiler::compile::h60c6b4594eb7955d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:562
  13:     0x56407ed61f74 - gluon_vm::compiler::Compiler::compile_::h543918283bcdae2d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:740
  14:     0x56407ed5f6c2 - gluon_vm::compiler::Compiler::compile::h60c6b4594eb7955d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:562
  15:     0x56407ed61f74 - gluon_vm::compiler::Compiler::compile_::h543918283bcdae2d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:740
  16:     0x56407ed5f6c2 - gluon_vm::compiler::Compiler::compile::h60c6b4594eb7955d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:562
  17:     0x56407ed61f74 - gluon_vm::compiler::Compiler::compile_::h543918283bcdae2d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:740
  18:     0x56407ed5f6c2 - gluon_vm::compiler::Compiler::compile::h60c6b4594eb7955d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:562
  19:     0x56407ed61f74 - gluon_vm::compiler::Compiler::compile_::h543918283bcdae2d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:740
  20:     0x56407ed5f6c2 - gluon_vm::compiler::Compiler::compile::h60c6b4594eb7955d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:562
  21:     0x56407ed61f74 - gluon_vm::compiler::Compiler::compile_::h543918283bcdae2d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:740
  22:     0x56407ed5f6c2 - gluon_vm::compiler::Compiler::compile::h60c6b4594eb7955d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:562
  23:     0x56407ed61f74 - gluon_vm::compiler::Compiler::compile_::h543918283bcdae2d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:740
  24:     0x56407ed5f6c2 - gluon_vm::compiler::Compiler::compile::h60c6b4594eb7955d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:562
  25:     0x56407ed5ec05 - gluon_vm::compiler::Compiler::compile_expr::hf16af474fd49f3a9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.6.0/src/compiler.rs:516
  26:     0x56407e355948 - <gluon::compiler_pipeline::TypecheckValue<E> as gluon::compiler_pipeline::Compileable<Extra>>::compile::h49e68615128ed22a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.6.0/src/compiler_pipeline.rs:253
  27:     0x56407e35e88b - <T as gluon::compiler_pipeline::Compileable<core::option::Option<&'b gluon_base::types::ArcType>>>::compile::{{closure}}::h3001a345fd6cc673
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.6.0/src/compiler_pipeline.rs:216
  28:     0x56407e39b849 - <core::result::Result<T, E>>::and_then::hec53eb245cb690f7
                               at /checkout/src/libcore/result.rs:602
  29:     0x56407e35e70c - <T as gluon::compiler_pipeline::Compileable<core::option::Option<&'b gluon_base::types::ArcType>>>::compile::hac61be42af971854
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.6.0/src/compiler_pipeline.rs:214
  30:     0x56407e448583 - <C as gluon::compiler_pipeline::Executable<'vm, Extra>>::run_expr::h27857bc3bbe4efa5
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.6.0/src/compiler_pipeline.rs:308
  31:     0x56407e3f9cee - gluon::Compiler::run_io_expr_async::h532d18024ff3f4df
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.6.0/src/lib.rs:474
  32:     0x56407e3f9b9d - gluon::Compiler::run_io_expr::h5767715228d6b608
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.6.0/src/lib.rs:460
  33:     0x56407e485b43 - osprey::bindings::run_code::h39d224efe0c26592
                               at src/bindings.rs:285
  34:     0x56407e486110 - osprey::osprey::h32e8f337242c47ad
                               at src/main.rs:32
  35:     0x56407e486268 - osprey::main::h816a67bdac14c81f
                               at src/main.rs:37
  36:     0x56407f26fc0c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  37:     0x56407f26941a - std::rt::lang_start::h97aba2334c85f570
                               at /checkout/src/libstd/panicking.rs:458
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:59
  38:     0x56407e488522 - main
  39:     0x7f9732c9b82f - __libc_start_main
  40:     0x56407e34e258 - _start
  41:                0x0 - <unknown>
root@bee095af6bf9:~/osprey# 
```

**Comment by Marwes** [comment]
Huh, I'd expect this line to fail compilation

```
let IlConstantNew value bits = constant_new value bits
```

In gluon all identifiers which start with an uppercase letter refers to a data constructor `Some`, `None` etc. Since `IlConstantNew` is not defined anywhere it should be rejected at typechecking but it seems it is treated as a function.

So it actually should be trivial to reproduce as the following code should fail to compile due to `Constructor` not being defined.

```f#
let Constructor x = 1
0
```
