### ISSUE TITLE
Panic in apply_args

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#494]
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', base/src/types/mod.rs:1294:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:68
             at src/libstd/sys_common/backtrace.rs:57
             at src/libstd/panicking.rs:381
   2: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   3: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   5: std::panicking::try::do_call
             at src/libstd/panicking.rs:522
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:498
   7: core::ptr::drop_in_place
             at src/libcore/panicking.rs:71
   8: core::ptr::drop_in_place
             at src/libcore/panicking.rs:51
   9: <usize as core::ops::arith::Sub>::sub
             at base/src/types/mod.rs:1294
  10: gluon_check::typecheck::get_alias_app
             at check/src/typecheck.rs:2481
  11: gluon_check::typecheck::Typecheck::typecheck_lambda
             at check/src/typecheck.rs:1361
  12: gluon_check::typecheck::Typecheck::typecheck_bindings
             at check/src/typecheck.rs:1692
  13: gluon_check::typecheck::Typecheck::typecheck_
             at check/src/typecheck.rs:858
  14: gluon_check::typecheck::Typecheck::typecheck_opt
             at check/src/typecheck.rs:683
  15: gluon_check::typecheck::Typecheck::generalize_type_errors
```

**Comment by Marwes** [comment]
Fix
