### ISSUE TITLE
Enum serialization fails when using lowercase enum values

### ISSUE THREAD

**Issue by jgrowl** [gluon-lang/gluon#506]
I have an enum that I am trying to serialize (I've tried to simplify):

```
#[derive(Debug, Deserialize, Serialize)]
pub enum Core {
    Absent
}
```

Which I call in a .glu file:

```
let { Core } = import! "statehash/enum.glu"
let test = Absent
```

Everything works as expected, but for specific aesthetic reasons I thought I'd lower case the enum like so: 

```
#[derive(Debug, Deserialize, Serialize)]
pub enum Core {
    absent
}
```

and then call it like so:

```
let { Core } = import! "statehash/enum.glu"
let test = absent
```

This gives me this error:

```
➜  statehash git:(master) ✗ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/statehash`
thread 'main' panicked at 'Undefined variable `absent` in <top>. Please report an issue at https://github.com/gluon-lang/gluon/issues', /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:553:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::begin_panic
             at libstd/panicking.rs:402
   5: std::panicking::try::do_call
             at libstd/panicking.rs:349
   6: gluon_vm::compiler::Compiler::load_identifier::{{closure}}
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:553
   7: <core::option::Option<T>>::unwrap_or_else
             at /Users/travis/build/rust-lang/rust/src/libcore/option.rs:376
   8: gluon_vm::compiler::Compiler::load_identifier
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:552
   9: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:618
  10: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  11: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:626
  12: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  13: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  14: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  15: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  16: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  17: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  18: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  19: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  20: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  21: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  22: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  23: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  24: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  25: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  26: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  27: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  28: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  29: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  30: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  31: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  32: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  33: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  34: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  35: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  36: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  37: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  38: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  39: gluon_vm::compiler::Compiler::compile_
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:799
  40: gluon_vm::compiler::Compiler::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:595
  41: gluon_vm::compiler::Compiler::find_tag::{{closure}}
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.7.1/src/compiler.rs:538
  42: <gluon::compiler_pipeline::TypecheckValue<E> as gluon::compiler_pipeline::Compileable<Extra>>::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.7.1/src/compiler_pipeline.rs:324
  43: <T as gluon::compiler_pipeline::Compileable<core::option::Option<&'b gluon_base::types::ArcType>>>::compile::{{closure}}
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.7.1/src/compiler_pipeline.rs:274
  44: <core::result::Result<T, E>>::and_then
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:621
  45: <T as gluon::compiler_pipeline::Compileable<core::option::Option<&'b gluon_base::types::ArcType>>>::compile
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.7.1/src/compiler_pipeline.rs:273
  46: <C as gluon::compiler_pipeline::Executable<'vm, Extra>>::load_script
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.7.1/src/compiler_pipeline.rs:405
  47: gluon::Compiler::parse_partial_expr::{{closure}}
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.7.1/src/lib.rs:354
  48: gluon::Compiler::parse_partial_expr::{{closure}}
             at /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.7.1/src/lib.rs:345
  49: statehash::main_
             at src/main.rs:69
  50: statehash::main
             at src/main.rs:41
  51: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  52: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  53: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  54: rust_panic
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  55: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  56: statehash::main_
```

I thought maybe I'd leave it uppercase, but change the serde option to lowercase when it serializes like so:

```
#[serde(rename_all = "lowercase")]
#[derive(Debug, Deserialize, Serialize)]
pub enum Core {
    Absent
}
```

It still throws an error when I use the lowercase version in the .glu file even though I can see it gets serialized as lowercase.

This isn't a big issue, just thought I'd mention it since lowercase enum values are still valid in rust.

Thanks!

**Comment by Marwes** [comment]
Thanks for reporting!

This is actually caused by the fact that gluon only allows and assumes that all enum variants starts with an uppercase letter. Unfortunately it seems that it is possible to circumvent that quite easily using the serde integration :( . Need to add a check somewhere to at least panic at the point that the type is created (and document that it must be uppercase).

Long term I want to do some changes to how enums(variants) work and I may allow lowercase variants then (or at least provide a similar "serde = lowercase" flag)

**Comment by Marwes** [comment]
cc #333
