### ISSUE TITLE
Script causes panic

### ISSUE THREAD

**Issue by tyler-conrad** [gluon-lang/gluon#703]
There are a couple logic errors in this script but thought I would submit an issue as it does cause a panic.

```
let { assert_eq, run_io } = import! std.test
let { monad } = import! std.io
let list @ { List, show, eq } = import! std.list

let reverse xs =
    let reverse_ as bs =
        match as with
        | Nil -> bs
        | Cons c cs -> reverse_ cs (Cons c bs)

    match xs with
    | Nil -> Nil
    | l -> reverse_ l Nil

let replicate xs count =
    let repl x i out =
        if i == count
        then out
        else repl x (i + 1) (Cons x out)

    let replicate_ xs out =
        match xs with
        | Nil -> out
        | Cons y ys -> replicate_ ys (Cons (repl y count Nil) out)

    if count == 0
    then Nil
    else reverse (replicate_ xs Nil)

run_io (assert_eq (list.of [0, 0, 0, 1, 1, 1]) (replicate (list.of [0, 1]) 3))
```

With the following backtrace:

```
thread 'main' panicked at 'expected ValueRef to be an Int, got Data(Data(Tag(0))). Please report an issue at https://github.com/gluon-lang/gluon/issues', /home/tyler/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.11.1/src/api/mod.rs:750:1
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:353
   7: <gluon_vm::stack::StackFrame<'b, S>>::get_value
   8: <gluon_vm::thread::ExecuteContext<'b>>::execute_
   9: gluon_vm::thread::OwnedContext::execute
  10: <gluon_vm::thread::Thread as gluon_vm::thread::ThreadInternal>::call_thunk
  11: gluon_vm::thread::ThreadInternal::call_thunk_top
  12: <gluon::import::DefaultImporter as gluon::import::Importer>::import
  13: <gluon::import::Import<I>>::load_module
  14: gluon::Compiler::load_file_async
  15: gluon::Compiler::load_file
  16: gluon::main
  17: std::rt::lang_start::{{closure}}
  18: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  20: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  21: main
  22: __libc_start_main
  23: _start
```
gluon_repl 0.11.0

**Comment by Marwes** [comment]
Thanks for reporting! I will have a look as soon as I can.
