### ISSUE TITLE
Script panics

### ISSUE THREAD

**Issue by tyler-conrad** [gluon-lang/gluon#705]
Sorry to keep opening issues about panics but hopefully it is helpful.

```
let list @ { List, foldable } = import! std.list
let { thread_rng } = import! std.random
let { IO, monad, applicative } = import! std.io
let { (>>=) } = import! std.monad
let { wrap } = import! std.applicative
let { foldl, count } = import! std.foldable
let { assert_eq, run_io } = import! std.test
let { count, all, elem } = import! std.foldable
let { flip } = import! std.function

let at index xs =
    if index < 0
    then None
    else
        match xs with
        | Nil -> None
        | Cons y ys ->
            match index with
            | 0 -> Some y
            | _ -> at (index - 1) ys

let reverse xs =
    let reverse_ as bs =
        match as with
        | Nil -> bs
        | Cons c cs -> reverse_ cs (Cons c bs)

    match xs with
    | Nil -> Nil
    | l -> reverse_ l Nil

let extract x y =
    y >>= \b ->
        x >>= \z ->
            wrap (
                match z with
                | Nil -> Cons b z
                | a -> Cons b a
            )

let rand_select xs n =
    let l = count xs
    if l == 0
    then wrap Nil
    else
        let rand_select_ i out =
            if i == 0
            then out
            else rand_select_ (i - 1) (Cons ((thread_rng.gen_int_range 0 l) >>= (\x -> wrap (at x xs))) out)

        (foldl extract (wrap Nil) (rand_select_ n Nil)) >>= (\xs -> wrap (reverse xs))

do xs = rand_select (list.of [0, 1, 2]) 3
run_io (assert_eq True (all ((flip elem) (list.of [0, 1, 2])) xs))
```

```
thread 'main' panicked at 'expected ValueRef to be an Int, got Data(Data(Data(DataStruct { tag: 1, fields: [1] }))). Please report an issue at https://github.com/gluon-lang/gluon/issues', /home/tyler/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.11.2/src/api/mod.rs:750:1
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:353
   7: <gluon_vm::stack::StackFrame<'b, S>>::get_value
   8: <gluon_vm::thread::ExecuteContext<'b>>::execute_
   9: gluon_vm::thread::OwnedContext::execute
  10: <gluon_vm::thread::Thread as gluon_vm::thread::ThreadInternal>::call_function
  11: <gluon_vm::thread::Thread as gluon_vm::thread::ThreadInternal>::execute_io
  12: gluon_vm::thread::ThreadInternal::execute_io_top
  13: gluon::compiler_pipeline::run_io
  14: <futures::future::chain::Chain<A, B, C>>::poll
  15: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  16: <futures::future::chain::Chain<A, B, C>>::poll
  17: <futures::future::chain::Chain<A, B, C>>::poll
  18: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  19: futures::task_impl::std::set
  20: <std::thread::local::LocalKey<T>>::with
  21: futures::future::Future::wait
  22: <gluon::import::DefaultImporter as gluon::import::Importer>::import
  23: <gluon::import::Import<I>>::load_module
  24: gluon::Compiler::load_file_async
  25: gluon::Compiler::load_file
  26: gluon::main
  27: std::rt::lang_start::{{closure}}
  28: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  30: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  31: main
  32: __libc_start_main
  33: _start
```

gluon_repl 0.11.2

**Comment by tyler-conrad** [comment]
Thanks for looking in to these issues.
