### ISSUE TITLE
Thread::get_global() fails to lookup a function.

### ISSUE THREAD

**Issue by ababo** [gluon-lang/gluon#821]
Here is the minimal reproducable snippet:
```rust
use gluon::{new_vm, vm::api::FunctionRef, ThreadExt};

#[tokio::main]
async fn main() -> Result<(), ()> {
    let vm = new_vm();

    let text = r#"
        let fib n =
            if n #Int< 2
            then 1
            else fib (n #Int- 1) #Int+ fib (n #Int- 2)
        fib
    "#;

    vm.load_script("test", text).unwrap();

    vm.get_global::<FunctionRef<fn(u64) -> u64>>("fib").unwrap();

    Ok(())
}
```

I get  the following stack trace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UndefinedBinding("fib")', src/libcore/result.rs:1188:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: core::result::Result<T,E>::unwrap
             at ./home/buildozer/aports/community/rust/src/rustc-1.41.0-src/src/libcore/result.rs:956
  10: crawler::main::{{closure}}
             at crawler/src/main.rs:17
  11: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at ./home/buildozer/aports/community/rust/src/rustc-1.41.0-src/src/libstd/future.rs:43
  12: tokio::runtime::enter::Enter::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/enter.rs:100
  13: tokio::runtime::thread_pool::ThreadPool::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/thread_pool/mod.rs:93
  14: tokio::runtime::Runtime::block_on::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:413
  15: tokio::runtime::context::enter
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/context.rs:72
  16: tokio::runtime::handle::Handle::enter
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/handle.rs:34
  17: tokio::runtime::Runtime::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:408
  18: crawler::main
             at crawler/src/main.rs:3
  19: std::rt::lang_start::{{closure}}
             at ./home/buildozer/aports/community/rust/src/rustc-1.41.0-src/src/libstd/rt.rs:67
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
  22: std::rt::lang_start_internal
  23: std::rt::lang_start
             at ./home/buildozer/aports/community/rust/src/rustc-1.41.0-src/src/libstd/rt.rs:67
  24: main
  25: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Can it be linked with the fact that I run the code with `tokio`?

**Comment by Marwes** [comment]
```rust
    vm.load_script("test", text).unwrap();
```

This defines a global named `test`. `fib` is just the local name for the function. Change `test` to `fib` here and it will do what you expect.

**Comment by ababo** [comment]
Oh, so each script can return a single global value. Does it mean that if I need more globals I just need to load more scripts?

**Comment by ababo** [comment]
Another question, please. Can my global function use the previous local declarations? Hope so.

**Comment by Marwes** [comment]
You can use `import! my_module` to load in previously defined globals/files from disk.

**Comment by Marwes** [comment]
> Oh, so each script can return a single global value. Does it mean that if I need more globals I just need to load more scripts?

Yes, you can always bundle multiple values into records and store that record in a global.
