### ISSUE TITLE
'Undefined variable `0x189dc99afd0:match_pattern` when using `xor_shift_rng`

### ISSUE THREAD

**Issue by Shuenhoy** [gluon-lang/gluon#866]
Reproduction code:

```gluon
let { xor_shift_rng } = import! std.random
let seed = [0b, 0b, 0b, 0b, 0b, 0b, 0b, 0b, 0b, 0b, 0b, 0b, 0b, 0b, 0b, 0b]
let xor = xor_shift_rng.new seed

let test y = { x = y }
let { x = x2 } = test xor

{}
```
Execute the above code would get an error:

```
thread 'main' panicked at 'Undefined variable `0x189dc99afd0:match_pattern` in test_xor_shift_rng. Please report an issue at https://github.com/gluon-lang/gluon/issues', gluon_vm-0.16.1\src\compiler.rs:607:32
```

I only see this happen with `xor_shift_rng`.

**Comment by Shuenhoy** [comment]
BTW, if I try to execute this code in REPL line by line, I would get this error when I execute the third line `let xor = xor_shift_rng.new seed`

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("Userdata cannot be cloned")', gluon-0.16.1\src\query.rs:305:31
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', gluon_repl-0.16.1\src\repl.rs:582:14
```

Not sure if this is relevant or irrelevant.
